-- Smart Table Supabase schema
-- Run this full file in the Supabase SQL Editor for project:
-- https://soopgkjsapuraqvqwtly.supabase.co

create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'admin' check (role = 'admin'),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

create table if not exists public.restaurant_settings (
  singleton boolean primary key default true check (singleton),
  restaurant_name text not null default 'Smart Table',
  google_review_url text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.dining_tables (
  id uuid primary key default gen_random_uuid(),
  table_number text not null unique,
  label text,
  seats integer not null default 4 check (seats > 0),
  qr_token uuid not null unique default gen_random_uuid(),
  status text not null default 'available'
    check (status in ('available', 'occupied', 'cleaning', 'disabled')),
  active_session_id uuid,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  icon text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  is_system boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.menu_categories(id) on delete restrict,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  prep_time_minutes integer default 10 check (prep_time_minutes >= 0),
  is_available boolean not null default true,
  tags text[] default '{}',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.menu_items(id) on delete cascade,
  title text not null,
  description text,
  discount_type text not null
    check (discount_type in ('percentage', 'fixed', 'price_override')),
  discount_value numeric(10,2) not null check (discount_value >= 0),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  is_active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.customer_sessions (
  id uuid primary key default gen_random_uuid(),
  table_id uuid not null references public.dining_tables(id) on delete restrict,
  customer_name text not null,
  contact_number text not null,
  status text not null default 'active' check (status in ('active', 'paid', 'closed')),
  opened_at timestamptz not null default now(),
  paid_at timestamptz,
  closed_at timestamptz
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_tables_active_session_fk'
  ) then
    alter table public.dining_tables
      add constraint dining_tables_active_session_fk
      foreign key (active_session_id)
      references public.customer_sessions(id)
      on delete set null;
  end if;
end $$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.customer_sessions(id) on delete cascade,
  table_id uuid not null references public.dining_tables(id) on delete restrict,
  order_number bigint generated by default as identity,
  status text not null default 'placed'
    check (status in ('placed', 'preparing', 'served', 'paid', 'cancelled')),
  total_amount numeric(10,2) not null default 0,
  savings_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  offer_id uuid references public.offers(id) on delete set null,
  item_name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  original_unit_price numeric(10,2) not null check (original_unit_price >= 0),
  quantity integer not null check (quantity >= 0),
  line_total numeric(10,2) not null default 0,
  savings_total numeric(10,2) not null default 0,
  status text not null default 'placed'
    check (status in ('placed', 'change_pending', 'cancel_pending', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_change_requests (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.customer_sessions(id) on delete cascade,
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  request_type text not null check (request_type in ('cancel', 'update_quantity')),
  requested_quantity integer check (requested_quantity is null or requested_quantity > 0),
  reason text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  resolved_by uuid references auth.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_calls (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.customer_sessions(id) on delete cascade,
  table_id uuid not null references public.dining_tables(id) on delete restrict,
  customer_name text not null,
  contact_number text not null,
  message text not null default 'Customer requested staff assistance.',
  status text not null default 'pending' check (status in ('pending', 'acknowledged', 'done')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  title text not null,
  message text not null,
  table_id uuid references public.dining_tables(id) on delete set null,
  session_id uuid references public.customer_sessions(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  staff_call_id uuid references public.staff_calls(id) on delete set null,
  change_request_id uuid references public.order_change_requests(id) on delete set null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_restaurant_settings on public.restaurant_settings;
create trigger touch_restaurant_settings
before update on public.restaurant_settings
for each row execute function public.touch_updated_at();

drop trigger if exists touch_dining_tables on public.dining_tables;
create trigger touch_dining_tables
before update on public.dining_tables
for each row execute function public.touch_updated_at();

drop trigger if exists touch_menu_categories on public.menu_categories;
create trigger touch_menu_categories
before update on public.menu_categories
for each row execute function public.touch_updated_at();

drop trigger if exists touch_menu_items on public.menu_items;
create trigger touch_menu_items
before update on public.menu_items
for each row execute function public.touch_updated_at();

drop trigger if exists touch_offers on public.offers;
create trigger touch_offers
before update on public.offers
for each row execute function public.touch_updated_at();

drop trigger if exists touch_orders on public.orders;
create trigger touch_orders
before update on public.orders
for each row execute function public.touch_updated_at();

drop trigger if exists touch_order_items on public.order_items;
create trigger touch_order_items
before update on public.order_items
for each row execute function public.touch_updated_at();

create index if not exists idx_dining_tables_status on public.dining_tables(status);
create index if not exists idx_menu_items_category on public.menu_items(category_id);
create index if not exists idx_offers_item_live on public.offers(item_id, is_active, ends_at);
create index if not exists idx_customer_sessions_table on public.customer_sessions(table_id, status);
create index if not exists idx_orders_session on public.orders(session_id);
create index if not exists idx_order_items_order on public.order_items(order_id);
create index if not exists idx_change_requests_status on public.order_change_requests(status);
create index if not exists idx_staff_calls_status on public.staff_calls(status);
create index if not exists idx_notifications_unread on public.notifications(is_read, created_at desc);

insert into public.restaurant_settings (singleton, restaurant_name)
values (true, 'Smart Table')
on conflict (singleton) do nothing;

insert into public.menu_categories (name, slug, icon, sort_order, is_system)
values
  ('Drinks', 'drinks', 'CupSoda', 1, true),
  ('Desserts', 'desserts', 'CakeSlice', 2, true),
  ('Meals', 'meals', 'Utensils', 3, true)
on conflict (slug) do nothing;

create or replace function public.recalculate_order_total(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders
  set
    total_amount = coalesce((
      select sum(line_total)
      from public.order_items
      where order_id = p_order_id
        and status <> 'cancelled'
    ), 0),
    savings_amount = coalesce((
      select sum(savings_total)
      from public.order_items
      where order_id = p_order_id
        and status <> 'cancelled'
    ), 0)
  where id = p_order_id;
end;
$$;

create or replace function public.notify_admin(
  p_type text,
  p_title text,
  p_message text,
  p_table_id uuid default null,
  p_session_id uuid default null,
  p_order_id uuid default null,
  p_staff_call_id uuid default null,
  p_change_request_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_notification_id uuid;
begin
  insert into public.notifications (
    type,
    title,
    message,
    table_id,
    session_id,
    order_id,
    staff_call_id,
    change_request_id
  )
  values (
    p_type,
    p_title,
    p_message,
    p_table_id,
    p_session_id,
    p_order_id,
    p_staff_call_id,
    p_change_request_id
  )
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

create or replace function public.start_table_session(
  p_table_id uuid,
  p_customer_name text,
  p_contact_number text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table public.dining_tables%rowtype;
  v_session_id uuid;
begin
  select *
  into v_table
  from public.dining_tables
  where id = p_table_id
  for update;

  if not found then
    raise exception 'Table was not found.';
  end if;

  if v_table.status = 'disabled' then
    raise exception 'This table is not available.';
  end if;

  if v_table.active_session_id is not null or v_table.status = 'occupied' then
    raise exception 'This table is already occupied.';
  end if;

  insert into public.customer_sessions (table_id, customer_name, contact_number)
  values (p_table_id, nullif(trim(p_customer_name), ''), nullif(trim(p_contact_number), ''))
  returning id into v_session_id;

  update public.dining_tables
  set status = 'occupied',
      active_session_id = v_session_id
  where id = p_table_id;

  perform public.notify_admin(
    'table_occupied',
    'Table occupied',
    'Table ' || v_table.table_number || ' occupied by ' || p_customer_name || '.',
    p_table_id,
    v_session_id
  );

  return v_session_id;
end;
$$;

create or replace function public.place_order(
  p_session_id uuid,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.customer_sessions%rowtype;
  v_table public.dining_tables%rowtype;
  v_order_id uuid;
  v_line record;
  v_item public.menu_items%rowtype;
  v_offer public.offers%rowtype;
  v_offer_id uuid;
  v_quantity integer;
  v_unit_price numeric(10,2);
  v_savings numeric(10,2);
begin
  select *
  into v_session
  from public.customer_sessions
  where id = p_session_id
    and status = 'active';

  if not found then
    raise exception 'Active customer session was not found.';
  end if;

  select *
  into v_table
  from public.dining_tables
  where id = v_session.table_id;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item.';
  end if;

  insert into public.orders (session_id, table_id)
  values (v_session.id, v_session.table_id)
  returning id into v_order_id;

  for v_line in
    select *
    from jsonb_to_recordset(p_items)
      as x(menu_item_id uuid, quantity integer, offer_id uuid)
  loop
    v_quantity := greatest(coalesce(v_line.quantity, 1), 1);

    select *
    into v_item
    from public.menu_items
    where id = v_line.menu_item_id
      and is_available = true;

    if not found then
      raise exception 'One selected menu item is not available.';
    end if;

    v_offer_id := null;
    v_unit_price := v_item.price;
    v_savings := 0;

    if v_line.offer_id is not null then
      select *
      into v_offer
      from public.offers
      where id = v_line.offer_id
        and item_id = v_item.id
        and is_active = true
        and now() between starts_at and ends_at;

      if found then
        v_offer_id := v_offer.id;
        if v_offer.discount_type = 'percentage' then
          v_unit_price := greatest(0, round(v_item.price - (v_item.price * v_offer.discount_value / 100), 2));
        elsif v_offer.discount_type = 'fixed' then
          v_unit_price := greatest(0, round(v_item.price - v_offer.discount_value, 2));
        else
          v_unit_price := greatest(0, round(v_offer.discount_value, 2));
        end if;
        v_savings := greatest(0, v_item.price - v_unit_price);
      end if;
    end if;

    insert into public.order_items (
      order_id,
      menu_item_id,
      offer_id,
      item_name,
      unit_price,
      original_unit_price,
      quantity,
      line_total,
      savings_total
    )
    values (
      v_order_id,
      v_item.id,
      v_offer_id,
      v_item.name,
      v_unit_price,
      v_item.price,
      v_quantity,
      round(v_unit_price * v_quantity, 2),
      round(v_savings * v_quantity, 2)
    );
  end loop;

  perform public.recalculate_order_total(v_order_id);

  perform public.notify_admin(
    'order_placed',
    'New order placed',
    'Table ' || v_table.table_number || ' ordered. Customer: ' || v_session.customer_name || '.',
    v_table.id,
    v_session.id,
    v_order_id
  );

  return v_order_id;
end;
$$;

create or replace function public.call_staff(
  p_session_id uuid,
  p_message text default 'Customer requested staff assistance.'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.customer_sessions%rowtype;
  v_table public.dining_tables%rowtype;
  v_call_id uuid;
begin
  select *
  into v_session
  from public.customer_sessions
  where id = p_session_id
    and status = 'active';

  if not found then
    raise exception 'Active customer session was not found.';
  end if;

  select *
  into v_table
  from public.dining_tables
  where id = v_session.table_id;

  insert into public.staff_calls (
    session_id,
    table_id,
    customer_name,
    contact_number,
    message
  )
  values (
    v_session.id,
    v_table.id,
    v_session.customer_name,
    v_session.contact_number,
    coalesce(nullif(trim(p_message), ''), 'Customer requested staff assistance.')
  )
  returning id into v_call_id;

  perform public.notify_admin(
    'staff_call',
    'Staff requested',
    'Table ' || v_table.table_number || ' requested staff. Customer: ' || v_session.customer_name || '.',
    v_table.id,
    v_session.id,
    null,
    v_call_id
  );

  return v_call_id;
end;
$$;

create or replace function public.request_order_change(
  p_session_id uuid,
  p_order_item_id uuid,
  p_request_type text,
  p_requested_quantity integer default null,
  p_reason text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.customer_sessions%rowtype;
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
  v_table public.dining_tables%rowtype;
  v_request_id uuid;
begin
  if p_request_type not in ('cancel', 'update_quantity') then
    raise exception 'Invalid request type.';
  end if;

  if p_request_type = 'update_quantity' and coalesce(p_requested_quantity, 0) < 1 then
    raise exception 'Requested quantity must be at least 1.';
  end if;

  select *
  into v_session
  from public.customer_sessions
  where id = p_session_id
    and status = 'active';

  if not found then
    raise exception 'Active customer session was not found.';
  end if;

  select oi.*
  into v_item
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where oi.id = p_order_item_id
    and o.session_id = v_session.id
    and oi.status not in ('cancelled', 'change_pending', 'cancel_pending')
  for update;

  if not found then
    raise exception 'Order item cannot be changed right now.';
  end if;

  if exists (
    select 1
    from public.order_change_requests
    where order_item_id = p_order_item_id
      and status = 'pending'
  ) then
    raise exception 'A request for this item is already pending.';
  end if;

  select * into v_order from public.orders where id = v_item.order_id;
  select * into v_table from public.dining_tables where id = v_order.table_id;

  insert into public.order_change_requests (
    session_id,
    order_item_id,
    request_type,
    requested_quantity,
    reason
  )
  values (
    v_session.id,
    v_item.id,
    p_request_type,
    p_requested_quantity,
    p_reason
  )
  returning id into v_request_id;

  update public.order_items
  set status = case
    when p_request_type = 'cancel' then 'cancel_pending'
    else 'change_pending'
  end
  where id = v_item.id;

  perform public.notify_admin(
    'change_request',
    'Order change requested',
    'Table ' || v_table.table_number || ' requested ' || replace(p_request_type, '_', ' ') || ' for ' || v_item.item_name || '.',
    v_table.id,
    v_session.id,
    v_order.id,
    null,
    v_request_id
  );

  return v_request_id;
end;
$$;

create or replace function public.get_customer_session_summary(p_session_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.customer_sessions%rowtype;
  v_table public.dining_tables%rowtype;
  v_settings public.restaurant_settings%rowtype;
  v_orders jsonb;
  v_requests jsonb;
  v_calls jsonb;
  v_due numeric(10,2);
  v_saved numeric(10,2);
begin
  select *
  into v_session
  from public.customer_sessions
  where id = p_session_id;

  if not found then
    raise exception 'Customer session was not found.';
  end if;

  select * into v_table from public.dining_tables where id = v_session.table_id;
  select * into v_settings from public.restaurant_settings where singleton = true;

  select coalesce(jsonb_agg(
    to_jsonb(o) || jsonb_build_object(
      'items',
      coalesce((
        select jsonb_agg(to_jsonb(oi) order by oi.created_at asc)
        from public.order_items oi
        where oi.order_id = o.id
      ), '[]'::jsonb)
    )
    order by o.created_at desc
  ), '[]'::jsonb)
  into v_orders
  from public.orders o
  where o.session_id = v_session.id;

  select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc), '[]'::jsonb)
  into v_requests
  from public.order_change_requests r
  where r.session_id = v_session.id;

  select coalesce(jsonb_agg(to_jsonb(c) order by c.created_at desc), '[]'::jsonb)
  into v_calls
  from public.staff_calls c
  where c.session_id = v_session.id;

  select
    coalesce(sum(oi.line_total) filter (where oi.status <> 'cancelled'), 0),
    coalesce(sum(oi.savings_total) filter (where oi.status <> 'cancelled'), 0)
  into v_due, v_saved
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where o.session_id = v_session.id;

  return jsonb_build_object(
    'session', to_jsonb(v_session),
    'table', to_jsonb(v_table),
    'orders', v_orders,
    'change_requests', v_requests,
    'staff_calls', v_calls,
    'settings', to_jsonb(v_settings),
    'totals', jsonb_build_object(
      'due', v_due,
      'saved', v_saved
    )
  );
end;
$$;

create or replace function public.admin_approve_change_request(
  p_request_id uuid,
  p_admin_note text default 'Approved by admin.'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.order_change_requests%rowtype;
  v_item public.order_items%rowtype;
  v_order_id uuid;
  v_session public.customer_sessions%rowtype;
  v_table public.dining_tables%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  select *
  into v_request
  from public.order_change_requests
  where id = p_request_id
  for update;

  if not found or v_request.status <> 'pending' then
    raise exception 'Request is not pending.';
  end if;

  select *
  into v_item
  from public.order_items
  where id = v_request.order_item_id
  for update;

  v_order_id := v_item.order_id;

  if v_request.request_type = 'cancel' then
    update public.order_items
    set status = 'cancelled',
        quantity = 0,
        line_total = 0,
        savings_total = 0
    where id = v_item.id;
  else
    update public.order_items
    set status = 'placed',
        quantity = v_request.requested_quantity,
        line_total = round(unit_price * v_request.requested_quantity, 2),
        savings_total = round(greatest(0, original_unit_price - unit_price) * v_request.requested_quantity, 2)
    where id = v_item.id;
  end if;

  update public.order_change_requests
  set status = 'approved',
      admin_note = coalesce(nullif(trim(p_admin_note), ''), 'Approved by admin.'),
      resolved_by = auth.uid(),
      resolved_at = now()
  where id = v_request.id;

  perform public.recalculate_order_total(v_order_id);

  select s.* into v_session
  from public.customer_sessions s
  join public.orders o on o.session_id = s.id
  where o.id = v_order_id;

  select * into v_table from public.dining_tables where id = v_session.table_id;

  perform public.notify_admin(
    'change_approved',
    'Request approved',
    'Table ' || v_table.table_number || ' request approved for ' || v_item.item_name || '.',
    v_table.id,
    v_session.id,
    v_order_id,
    null,
    v_request.id
  );

  return v_request.id;
end;
$$;

create or replace function public.admin_reject_change_request(
  p_request_id uuid,
  p_admin_note text default 'Rejected because the order is already being prepared.'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.order_change_requests%rowtype;
  v_item public.order_items%rowtype;
  v_order_id uuid;
  v_session public.customer_sessions%rowtype;
  v_table public.dining_tables%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  select *
  into v_request
  from public.order_change_requests
  where id = p_request_id
  for update;

  if not found or v_request.status <> 'pending' then
    raise exception 'Request is not pending.';
  end if;

  select *
  into v_item
  from public.order_items
  where id = v_request.order_item_id
  for update;

  v_order_id := v_item.order_id;

  update public.order_items
  set status = 'placed'
  where id = v_item.id;

  update public.order_change_requests
  set status = 'rejected',
      admin_note = coalesce(nullif(trim(p_admin_note), ''), 'Rejected because the order is already being prepared.'),
      resolved_by = auth.uid(),
      resolved_at = now()
  where id = v_request.id;

  perform public.recalculate_order_total(v_order_id);

  select s.* into v_session
  from public.customer_sessions s
  join public.orders o on o.session_id = s.id
  where o.id = v_order_id;

  select * into v_table from public.dining_tables where id = v_session.table_id;

  perform public.notify_admin(
    'change_rejected',
    'Request rejected',
    'Table ' || v_table.table_number || ' request rejected for ' || v_item.item_name || '.',
    v_table.id,
    v_session.id,
    v_order_id,
    null,
    v_request.id
  );

  return v_request.id;
end;
$$;

create or replace function public.admin_close_paid_session(p_session_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.customer_sessions%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  select *
  into v_session
  from public.customer_sessions
  where id = p_session_id
  for update;

  if not found then
    raise exception 'Session was not found.';
  end if;

  update public.customer_sessions
  set status = 'paid',
      paid_at = coalesce(paid_at, now()),
      closed_at = now()
  where id = v_session.id;

  update public.dining_tables
  set status = 'available',
      active_session_id = null
  where id = v_session.table_id
    and active_session_id = v_session.id;

  perform public.notify_admin(
    'bill_paid',
    'Bill paid',
    'A bill was marked paid and the table was released.',
    v_session.table_id,
    v_session.id
  );

  return v_session.id;
end;
$$;

alter table public.admin_profiles enable row level security;
alter table public.restaurant_settings enable row level security;
alter table public.dining_tables enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.offers enable row level security;
alter table public.customer_sessions enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_change_requests enable row level security;
alter table public.staff_calls enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Admins can read admin profiles" on public.admin_profiles;
create policy "Admins can read admin profiles"
on public.admin_profiles for select
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can manage admin profiles" on public.admin_profiles;
create policy "Admins can manage admin profiles"
on public.admin_profiles for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read settings" on public.restaurant_settings;
create policy "Public can read settings"
on public.restaurant_settings for select
using (true);

drop policy if exists "Admins can manage settings" on public.restaurant_settings;
create policy "Admins can manage settings"
on public.restaurant_settings for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active tables" on public.dining_tables;
create policy "Public can read active tables"
on public.dining_tables for select
using (status <> 'disabled');

drop policy if exists "Admins can manage tables" on public.dining_tables;
create policy "Admins can manage tables"
on public.dining_tables for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active categories" on public.menu_categories;
create policy "Public can read active categories"
on public.menu_categories for select
using (is_active = true);

drop policy if exists "Admins can manage categories" on public.menu_categories;
create policy "Admins can manage categories"
on public.menu_categories for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read available items" on public.menu_items;
create policy "Public can read available items"
on public.menu_items for select
using (is_available = true);

drop policy if exists "Admins can manage items" on public.menu_items;
create policy "Admins can manage items"
on public.menu_items for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active offers" on public.offers;
create policy "Public can read active offers"
on public.offers for select
using (is_active = true);

drop policy if exists "Admins can manage offers" on public.offers;
create policy "Admins can manage offers"
on public.offers for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read sessions" on public.customer_sessions;
create policy "Admins can read sessions"
on public.customer_sessions for select
using (public.is_admin());

drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders"
on public.orders for select
using (public.is_admin());

drop policy if exists "Admins can read order items" on public.order_items;
create policy "Admins can read order items"
on public.order_items for select
using (public.is_admin());

drop policy if exists "Admins can read change requests" on public.order_change_requests;
create policy "Admins can read change requests"
on public.order_change_requests for select
using (public.is_admin());

drop policy if exists "Admins can read staff calls" on public.staff_calls;
create policy "Admins can read staff calls"
on public.staff_calls for select
using (public.is_admin());

drop policy if exists "Admins can update staff calls" on public.staff_calls;
create policy "Admins can update staff calls"
on public.staff_calls for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read notifications" on public.notifications;
create policy "Admins can read notifications"
on public.notifications for select
using (public.is_admin());

drop policy if exists "Admins can update notifications" on public.notifications;
create policy "Admins can update notifications"
on public.notifications for update
using (public.is_admin())
with check (public.is_admin());

grant execute on function public.start_table_session(uuid, text, text) to anon, authenticated;
grant execute on function public.place_order(uuid, jsonb) to anon, authenticated;
grant execute on function public.call_staff(uuid, text) to anon, authenticated;
grant execute on function public.request_order_change(uuid, uuid, text, integer, text) to anon, authenticated;
grant execute on function public.get_customer_session_summary(uuid) to anon, authenticated;
grant execute on function public.admin_approve_change_request(uuid, text) to authenticated;
grant execute on function public.admin_reject_change_request(uuid, text) to authenticated;
grant execute on function public.admin_close_paid_session(uuid) to authenticated;

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read menu images" on storage.objects;
create policy "Public can read menu images"
on storage.objects for select
using (bucket_id = 'menu-images');

drop policy if exists "Admins can upload menu images" on storage.objects;
create policy "Admins can upload menu images"
on storage.objects for insert
with check (bucket_id = 'menu-images' and public.is_admin());

drop policy if exists "Admins can update menu images" on storage.objects;
create policy "Admins can update menu images"
on storage.objects for update
using (bucket_id = 'menu-images' and public.is_admin())
with check (bucket_id = 'menu-images' and public.is_admin());

drop policy if exists "Admins can delete menu images" on storage.objects;
create policy "Admins can delete menu images"
on storage.objects for delete
using (bucket_id = 'menu-images' and public.is_admin());

do $$
declare
  rel_name text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach rel_name in array array[
      'notifications',
      'orders',
      'order_items',
      'order_change_requests',
      'staff_calls',
      'customer_sessions',
      'dining_tables'
    ]
    loop
      if not exists (
        select 1
        from pg_publication_rel pr
        join pg_class c on c.oid = pr.prrelid
        join pg_namespace n on n.oid = c.relnamespace
        join pg_publication p on p.oid = pr.prpubid
        where p.pubname = 'supabase_realtime'
          and n.nspname = 'public'
          and c.relname = rel_name
      ) then
        execute format('alter publication supabase_realtime add table public.%I', rel_name);
      end if;
    end loop;
  end if;
end $$;

-- After creating the first admin in Authentication > Users, run this snippet:
-- insert into public.admin_profiles (user_id, full_name, role)
-- select id, 'Restaurant Admin', 'admin'
-- from auth.users
-- where email = 'YOUR_ADMIN_EMAIL@example.com'
-- on conflict (user_id) do update set role = 'admin';
